### ISSUE TITLE
API is returning 500 Internal Server Error

### ISSUE THREAD

**Issue by tmtmtmtm** [KohoVolit/api.parldata.eu#11]
For the last few days, http://api.parldata.eu/ has been returning an Internal Server Error

**Comment by girogiro** [comment]
Fixed, thanks.

TokuMX restarted. Periodic restart would be probably useful to schedule because TokuMX sometimes runs into some memory issues.

**Comment by girogiro** [comment]
Now there is a periodic check (every 10 mins) that API is running. If returning 500 Internal Server Error, TokuMX is restarted. Hence, there should be no downtimes of the API longer than 10 mins in the future.

The monitoring is implemented in `/etc/cron.d/restart_api_if_needed` .
