### ISSUE TITLE
API is returning 500 Internal Server Error again

### ISSUE THREAD

**Issue by tmtmtmtm** [KohoVolit/api.parldata.eu#12]
This time it can get to any of the main index pages (e.g. http://api.parldata.eu/kv/kuvendi/)  but anything deeper (e.g. http://api.parldata.eu/kv/kuvendi/organizations/) returns 500

**Comment by michalskop** [comment]
It required restart of tokumx. I am recently adding Czech voting records (will be done in a couple of hours, if everything goes ok) and tokumx regularly crashes after adding some 7000 vote events (i.e., 7000*200 votes). We should probably add a regular check whether tokumx needs restart.

**Comment by girogiro** [comment]
I created a periodic check (every 10 mins) that API is running. If returning 500 Internal Server Error, TokuMX is restarted. Hence, there should be no downtimes of the API longer than 10 mins in the future.

The monitoring is implemented in `/etc/cron.d/restart_api_if_needed` .
