### ISSUE TITLE
Event could have many identifiers

### ISSUE THREAD

**Issue by KrzysztofMadejski** [KohoVolit/api.parldata.eu#5]
In https://github.com/KohoVolit/api.parldata.eu/blob/master/schemas/event.py
```
'identifiers': {
			# Issued identifiers
			'type': 'list',
			'schema': {
				'type': 'dict',
				'schema': identifier.schema,
			},
			'unique_elements': True,
		},
```

instead of

```
'identifier': {
			# An issued identifier
			'type': 'string',
			'nullable': True,
		},
```

My use case: To map `source url id` and `no.`.

It's breaking change so we have to ensure nobody is using this field.

**Comment by girogiro** [comment]
The Event class is not part of Popolo yet and I tried to maintain maximum compatibility with the existing VoteEvent class that should be subclass of the Event. And there is a single identifier in VoteEvent schema.

Source ID is present in `source.url` property, serial number goes to `identifier`. Presence can be tested by whole `source.url` or for querying by only source ID see: https://github.com/KohoVolit/scraper-sk_nrsr/issues/1

Is this OK for you?

**Comment by KrzysztofMadejski** [comment]
It's ok. Maybe I should take part in discussion about Popolo and propose that. It's kind of incompatibility inside Popolo for me.

**Comment by akuckartz** [comment]
Using JSON-LD might solve that issue.
