### ISSUE TITLE
Event: Use classification instead of type?

### ISSUE THREAD

**Issue by jpmckinney** [KohoVolit/api.parldata.eu#7]
Just learned of the Event schema here. Popolo would very likely use `classification` instead of `type`. Otherwise I think it would match your schema.

By the way, all the research for an Event schema is done; I just haven't found the time to sit down and write up the spec.

**Comment by girogiro** [comment]
I considered both `classification` and `type` and have chosen `type` because of https://github.com/popolo-project/popolo-spec/issues/74#issuecomment-64258753. Doesn't it apply to events?

**Comment by jpmckinney** [comment]
For Speech and ContactDetail, the `type` property is an alias for `rdf:type` and points to an RDF class. The reason for this is that the Speech and ContactDetail RDF classes all have identical properties, and instead of replicating these multiple classes in the JSON serialization (which would make things unnecessarily complicated), we just refer to the real class with `type`.

For all other classes, we use `classification` which is an alias for `ncal:categories` for Event, `gn:featureCode` for Feature, `schema:additionalType` for Motion and `org:classification` for Organization. In these cases, if we wanted to extend a class into a subclass (for example, VoteEvent is a subclass of Event), we need to leave the `rdf:type` property available.

Popolo's draft Event class is now at http://www.popoloproject.com/specs/event.html

**Comment by jpmckinney** [comment]
Why was this closed? It's still an open issue: https://github.com/KohoVolit/api.parldata.eu/blob/master/schemas/event.py#L35

**Comment by girogiro** [comment]
It was moved to a more specific issue #9.
