### ISSUE TITLE
UTC time - vpapi

### ISSUE THREAD

**Issue by michalskop** [KohoVolit/api.parldata.eu#8]
vpapi.local_to_utc("2013-11-27T10:10:00")
returns an error.
there should probably be;
if not isinstance(out, datetime):
and not
if not isinstance(val, datetime):

Btw: Is there any potentional real-world use of the all UTC time-requirement for this data?
I 'd propose to drop this requirement.

**Comment by girogiro** [comment]
Fixed, thanks.

The UTC time is used in API for consistency of object fields - `created_at` and `updated_at` are set automatically by server in UTC time; if other datetime fields were in a different timezone, votes that were created before they were cast could appear in the database. It's also a recommended best practice to use always UTC time in APIs.

**Comment by akuckartz** [comment]
@girogiro Can you provide a link to that recommendation?

**Comment by girogiro** [comment]
Here are two sources:
http://apiux.com/2013/03/20/5-laws-api-dates-and-times/
http://stackoverflow.com/questions/2532729/daylight-saving-time-and-time-zone-best-practices

The decision was also influenced by the facts that MongoDB cannot save timezone (it uses Unix epoch value internally) and that [Eve] (http://python-eve.org) requires identical datetime format for both input and output.
